export const liquData = [
  {
    TIME: "Mar-23",
    "Game Output": "0.0",
    IEO: "10.0",
    Marketing: "0.0",
    "Pre-sale": "0.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "0.0",
  },
  {
    TIME: "Apr-23",
    "Game Output": "0.3",
    IEO: "10.0",
    Marketing: "0.0",
    "Pre-sale": "1.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "0.0",
  },
  {
    TIME: "May-23",
    "Game Output": "0.6",
    IEO: "10.0",
    Marketing: "0.0",
    "Pre-sale": "2.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "0.2",
  },
  {
    TIME: "Jun-23",
    "Game Output": "0.9",
    IEO: "10.0",
    Marketing: "1.0",
    "Pre-sale": "3.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "0.4",
  },
  {
    TIME: "Jul-23",
    "Game Output": "1.3",
    IEO: "10.0",
    Marketing: "2.0",
    "Pre-sale": "4.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "0.6",
  },
  {
    TIME: "Aug-23",
    "Game Output": "1.7",
    IEO: "10.0",
    Marketing: "3.0",
    "Pre-sale": "5.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "0.8",
  },
  {
    TIME: "Sep-23",
    "Game Output": "2.1",
    IEO: "10.0",
    Marketing: "3.0",
    "Pre-sale": "6.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "1.0",
  },
  {
    TIME: "Oct-23",
    "Game Output": "2.6",
    IEO: "10.0",
    Marketing: "3.0",
    "Pre-sale": "7.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "1.2",
  },
  {
    TIME: "Nov-23",
    "Game Output": "3.1",
    IEO: "10.0",
    Marketing: "3.0",
    "Pre-sale": "8.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "1.4",
  },
  {
    TIME: "Dec-23",
    "Game Output": "3.6",
    IEO: "10.0",
    Marketing: "3.3",
    "Pre-sale": "9.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "1.6",
  },
  {
    TIME: "Jan-24",
    "Game Output": "4.1",
    IEO: "10.0",
    Marketing: "3.6",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "1.8",
  },
  {
    TIME: "Feb-24",
    "Game Output": "4.6",
    IEO: "10.0",
    Marketing: "3.9",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "2.0",
  },
  {
    TIME: "Mar-24",
    "Game Output": "5.1",
    IEO: "10.0",
    Marketing: "4.2",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "2.2",
  },
  {
    TIME: "Apr-24",
    "Game Output": "5.6",
    IEO: "10.0",
    Marketing: "4.5",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "0.0",
    "User Creation": "2.4",
  },
  {
    TIME: "May-24",
    "Game Output": "6.1",
    IEO: "10.0",
    Marketing: "4.8",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "0.5",
    "User Creation": "2.6",
  },
  {
    TIME: "Jun-24",
    "Game Output": "6.6",
    IEO: "10.0",
    Marketing: "5.1",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "1.0",
    "User Creation": "2.8",
  },
  {
    TIME: "Jul-24",
    "Game Output": "7.1",
    IEO: "10.0",
    Marketing: "5.4",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "1.5",
    "User Creation": "3.0",
  },
  {
    TIME: "Aug-24",
    "Game Output": "7.6",
    IEO: "10.0",
    Marketing: "5.7",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "2.0",
    "User Creation": "3.2",
  },
  {
    TIME: "Sep-24",
    "Game Output": "8.1",
    IEO: "10.0",
    Marketing: "6.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "2.5",
    "User Creation": "3.4",
  },
  {
    TIME: "Oct-24",
    "Game Output": "8.6",
    IEO: "10.0",
    Marketing: "6.3",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "3.0",
    "User Creation": "3.6",
  },
  {
    TIME: "Nov-24",
    "Game Output": "9.1",
    IEO: "10.0",
    Marketing: "6.6",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "3.5",
    "User Creation": "3.8",
  },
  {
    TIME: "Dec-24",
    "Game Output": "9.6",
    IEO: "10.0",
    Marketing: "6.9",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "4.0",
    "User Creation": "4.0",
  },
  {
    TIME: "Jan-25",
    "Game Output": "10.1",
    IEO: "10.0",
    Marketing: "7.2",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "4.5",
    "User Creation": "4.2",
  },
  {
    TIME: "Feb-25",
    "Game Output": "10.6",
    IEO: "10.0",
    Marketing: "7.5",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "5.0",
    "User Creation": "4.4",
  },
  {
    TIME: "Mar-25",
    "Game Output": "11.1",
    IEO: "10.0",
    Marketing: "7.8",
    "Pre-sale": "10.0",
    "Team&Consultant": "0.0",
    Investor: "5.5",
    "User Creation": "4.6",
  },
  {
    TIME: "Apr-25",
    "Game Output": "11.6",
    IEO: "10.0",
    Marketing: "8.1",
    "Pre-sale": "10.0",
    "Team&Consultant": "1.0",
    Investor: "6.0",
    "User Creation": "4.8",
  },
  {
    TIME: "May-25",
    "Game Output": "12.1",
    IEO: "10.0",
    Marketing: "8.4",
    "Pre-sale": "10.0",
    "Team&Consultant": "2.0",
    Investor: "6.5",
    "User Creation": "5.0",
  },
  {
    TIME: "Jun-25",
    "Game Output": "12.6",
    IEO: "10.0",
    Marketing: "8.7",
    "Pre-sale": "10.0",
    "Team&Consultant": "3.0",
    Investor: "7.0",
    "User Creation": "5.2",
  },
  {
    TIME: "Jul-25",
    "Game Output": "13.1",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "4.0",
    Investor: "7.5",
    "User Creation": "5.4",
  },
  {
    TIME: "Aug-25",
    "Game Output": "13.6",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "5.0",
    Investor: "8.0",
    "User Creation": "5.6",
  },
  {
    TIME: "Sep-25",
    "Game Output": "14.1",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "6.0",
    Investor: "8.5",
    "User Creation": "5.8",
  },
  {
    TIME: "Oct-25",
    "Game Output": "14.6",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "7.0",
    Investor: "9.0",
    "User Creation": "6.0",
  },
  {
    TIME: "Nov-25",
    "Game Output": "15.1",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "8.0",
    Investor: "9.5",
    "User Creation": "6.2",
  },
  {
    TIME: "Dec-25",
    "Game Output": "15.6",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "9.0",
    Investor: "10.0",
    "User Creation": "6.4",
  },
  {
    TIME: "Jan-26",
    "Game Output": "16.1",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "10.0",
    Investor: "10.0",
    "User Creation": "6.6",
  },
  {
    TIME: "Feb-26",
    "Game Output": "16.6",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "11.0",
    Investor: "10.0",
    "User Creation": "6.8",
  },
  {
    TIME: "Mar-26",
    "Game Output": "17.1",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "12.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Apr-26",
    "Game Output": "17.6",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "13.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "May-26",
    "Game Output": "18.1",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "14.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Jun-26",
    "Game Output": "18.6",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "15.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Jul-26",
    "Game Output": "19.1",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "16.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Aug-26",
    "Game Output": "19.6",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "17.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Sep-26",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "18.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Oct-26",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "19.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Nov-26",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "20.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Dec-26",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "21.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Jan-27",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "22.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Feb-27",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "23.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Mar-27",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "24.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Apr-27",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "24.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "May-27",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "24.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Jun-27",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "24.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Jul-27",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "24.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
  {
    TIME: "Aug-27",
    "Game Output": "20.0",
    IEO: "10.0",
    Marketing: "9.0",
    "Pre-sale": "10.0",
    "Team&Consultant": "24.0",
    Investor: "10.0",
    "User Creation": "7.0",
  },
];
